name: GitHub Actions Demo
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on: [push]
jobs:
  Test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.11", "3.12"]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Setup and Flake8 testing
        run: pip install flake8 && flake8 .

      - name: Running Tests with ${{ matrix.python-version }}
        run: python -m unittest -v

      - name: Print status
        run: echo "🍏 This job's status is ${{ job.status }}."
